#import "@preview/subpar:0.2.0"

#let conclusion() = {
  text(lang:"en")[
    #show raw.where(block: true): block.with(
      fill: luma(240),
      inset: 10pt,
      radius: 4pt,
    )

    = Conclusion and Future Work
    In this research, computer vision techniques were systematically explored for the extraction of geometric features from nDSM data. 
    A set of key methods—spanning edge detection, segmentation, and morphological operations—were rigorously evaluated for their effectiveness in identifying fine-grained structural elements of building roofs to support precise segmentation. 
    The gradient method, used for derivative calculation, proved to be a reliable technique for detecting sharp transitions in elevation. 
    Techniques such as logarithmic scaling, clipping of extreme values, and blurring were empirically shown to reduce noise and enhance relevant features in the nDSM.

    The specific sequence of algorithmic steps was governed by hyperparameter configurations, which were tailored to the characteristics of each building. 
    To support this, an automated pipeline was developed to systematically explore and determine optimal parameter sets for feature extraction. 
    The quality of resulting segmentations was assessed through custom evaluation metrics based on geometric properties of the predicted masks. 
    This facilitated a comparative evaluation of the results, thereby enabling the selection of the most suitable parametrisation.
    The robustness of these metrics was validated against ground truth data.

    The performance of SAM was evaluated using input prompts generated by the proposed pipeline and compared to alternative prompting strategies, including manually defined and automatically generated prompts.
    Prompts derived from geometric features consistently led to improved segmentation performance, offering a more informed basis for guiding SAM.
    Various prompt generation techniques were tested across different image contexts, revealing that no single method or image consistently outperformed others. 
    Segmentation outcomes exhibited considerable variability depending on input image characteristics and the spatial complexity of roof structures.

    Moreover, the SAM confidence scores were identified as ineffective predictors of actual mask quality, due to the frequent divergence between confidence and observed segmentation accuracy.
    A promising direction that emerged during experimentation was the fusion of results from multiple prompting strategies, which yielded improved outcomes in most cases. 
    The development of a more principled and robust method for combining prompts is an area that requires further research.


    // -> more extensive research on the configurations of sam input prompts especially negative ones
    // -> more educated approach of combining the different sam input prompts
  ]
}