#import "@preview/subpar:0.2.0"

#let conclusion() = {
  text(lang:"en")[
    #show raw.where(block: true): block.with(
      fill: luma(240),
      inset: 10pt,
      radius: 4pt,
    )

    = Conclusion and Future Work
    In this research, computer vision techniques were systematically explored for the extraction of geometric features from nDSM data. 
    A set of key methods—spanning edge detection, segmentation, and morphological operations—were rigorously evaluated for their effectiveness in identifying fine-grained structural elements of building roofs to support precise segmentation. 
    The gradient method, used for derivative calculation, proved to be a reliable technique for detecting sharp transitions in elevation. 
    Techniques such as logarithmic scaling, clipping of extreme values, and blurring were empirically shown to reduce noise and enhance relevant features in the nDSM.

    The specific sequence of algorithmic steps was governed by hyperparameter configurations, which were tailored to the characteristics of each building. 
    To support this, an automated pipeline was developed to systematically explore and determine optimal parameter sets for feature extraction. 
    The quality of resulting segmentations was assessed through custom evaluation metrics based on geometric properties of the predicted masks. 
    This facilitated a comparative evaluation of the results, thereby enabling the selection of the most suitable parametrisation.
    The robustness of these metrics was validated against ground truth data.

    The performance of SAM was evaluated using input prompts generated by the proposed pipeline and compared to alternative prompting strategies, including manually defined and automatically generated prompts.
    Prompts derived from geometric features consistently led to improved segmentation performance, offering a more informed basis for guiding SAM.
    Various prompt generation techniques were tested across different image contexts, revealing that no single method or image consistently outperformed others. 
    Segmentation outcomes exhibited considerable variability depending on input image characteristics and the spatial complexity of roof structures.
    Moreover, the SAM confidence scores were identified as ineffective predictors of actual mask quality, due to the frequent divergence between confidence and observed segmentation accuracy.
    A promising direction that emerged during experimentation was the fusion of results from multiple prompting strategies, which yielded improved outcomes in most cases.

    A range of potential future research initiatives have been identified.
    Further investigation is indicated into the various strategies that have been established in this study for prompting SAM via input points.
    This is particularly evident in the context of negative prompts, which remain under-explored but may hold untapped potential for improving segmentation precision.
    Exploration of more dynamic decision-making processes for selecting the most effective prompting strategies would be advantageous.
    This is particularly evident in the more sophisticated approach of identifying the most valuable negative inputs, as opposed to the approach that has been employed here.

    It is recommended that further investigation be conducted into the development of a more principled and robust method for combining prompts.
    Whilst the present study demonstrated that the fusion of different prompts derived from distinct input images can lead to improved segmentation results, the process of combination was not conducted in a sufficiently sophisticated manner.
    The utilisation of the proposed scoring system for individual mask evaluation as a substitute for the scores provided by SAM remains an unexplored prospect.
    A more systematic approach has the potential to optimise the integration of diverse prompt sources and yield more consistent improvements.
    Furthermore, the observed benefits of combining masks generated from multiple input images hold considerable promise.
    It is indicated that a decision-based system could be utilised to combine different prompting strategies.
    It is recommended that future research endeavours focus on the optimisation of the utilisation of the complementary strengths of diverse images and prompt types.

    It is suggested that a future direction for research in this field might be to develop a classification system for roof types based on the segmentations generated in this study.
    Whilst the original input data encompassed a broad spectrum of buildings and roof structures, the associated classifications were frequently unreliable or inconsistent, and did not accurately reflect the actual geometric characteristics.
    Nevertheless, the segmentations produced by the developed pipeline and SAM offer a more sophisticated representation of roof geometry, which could serve as a more reliable foundation for the classification of roof types.

    A systematic evaluation of performance across a broader range of roof structures remains largely unexplored; further research is required in this area.
    The primary focus of this thesis was conventional roof shapes and flat roofs, with a particular emphasis on smaller segments.
    Geometries of a more unusual character, such as rounded roofs, have not been the subject of detailed study, yet these may present unique challenges and insights.
    A targeted investigation into the extent to which the algorithms under discussion are able to handle such variations could reveal significant limitations or adaptations required for broader applicability.
  ]
}